# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
    - main
    - 'feature/**'
  pull_request:
    branches:
    - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
# concurrency:
#   group: "pages"
#   cancel-in-progress: true

jobs:
  build:
    name: Build Apps

    runs-on: ubuntu-latest

    steps:
      # - name: Check events
      #   shell: bash
      #   run: |
      #     echo "${{ github.event_name }}"
      #     echo "${{ github.ref }}"
      #     echo "${{ github.ref_name }}"

      - name: Checkout
        uses: actions/checkout@v3

      # - name: Setup Pages
      #   uses: actions/configure-pages@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.x'

      - name: Restore NuGet packages
        shell: bash
        run: |
          dotnet restore .

      - name: Build solution
        shell: bash
        run: |
          dotnet build .

      - name: Test solution
        shell: bash
        run: |
          dotnet test . -c Release

      - name: Publish artifact
        if: github.event_name == 'push' && github.ref_name == 'main'
        shell: bash
        run: |
          dotnet publish ./src/Fitability.Home -c Release -o published

      - name: Upload artifact
        if: github.event_name == 'push' && github.ref_name == 'main'
        uses: actions/upload-pages-artifact@v1
        with:
          path: published/wwwroot

  deploy:
    name: Deploy to Pages
    if: github.event_name == 'push' && github.ref_name == 'main'

    needs:
    - build

    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
